import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

interface GameInfo {
  id: string
  name: string
  path: string
  preview: string | null
}

function formatGameName(folderName: string): string {
  return folderName
    .split('-')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ')
}

function findPreviewImage(distDir: string, gameId: string, previewsDir: string): string | null {
  const extensions = ['.png', '.jpg', '.jpeg', '.gif', '.webp']

  // Check in public/previews folder first
  for (const ext of extensions) {
    const previewPath = path.join(previewsDir, `${gameId}${ext}`)
    if (fs.existsSync(previewPath)) {
      return `./previews/${gameId}${ext}`
    }
  }

  // Check in the game folder itself
  for (const ext of extensions) {
    const inGamePreview = path.join(distDir, gameId, `preview${ext}`)
    if (fs.existsSync(inGamePreview)) {
      return `./${gameId}/preview${ext}`
    }
  }

  return null
}

function discoverGames(): GameInfo[] {
  const distDir = path.resolve(__dirname, '../dist')
  const previewsDir = path.resolve(__dirname, '../dist/previews')
  const games: GameInfo[] = []

  if (!fs.existsSync(distDir)) {
    console.log('No dist directory found')
    return games
  }

  const entries = fs.readdirSync(distDir, { withFileTypes: true })

  for (const entry of entries) {
    if (entry.isDirectory()) {
      const gameDir = path.join(distDir, entry.name)
      const indexPath = path.join(gameDir, 'index.html')

      // Skip if no index.html (not a game folder)
      if (!fs.existsSync(indexPath)) continue

      // Skip build artifacts
      if (entry.name === 'assets') continue

      const gameId = entry.name
      const preview = findPreviewImage(distDir, gameId, previewsDir)

      games.push({
        id: gameId,
        name: formatGameName(gameId),
        path: `./${gameId}/`,
        preview
      })
    }
  }

  return games.sort((a, b) => a.name.localeCompare(b.name))
}

// Generate the games data file
const games = discoverGames()
const output = `// Auto-generated by discover-games.ts
export interface GameInfo {
  id: string
  name: string
  path: string
  preview: string | null
}

export const games: GameInfo[] = ${JSON.stringify(games, null, 2)}
`

const outputPath = path.resolve(__dirname, '../src/games-data.ts')
fs.writeFileSync(outputPath, output)
console.log(`Discovered ${games.length} game(s):`)
games.forEach(g => console.log(`  - ${g.name} (${g.id})`))
