// Auto-generated by discover-games.ts
export interface GameInfo {
  id: string
  name: string
  path: string
  preview: string | null
}

export const games: GameInfo[] = [
  {
    "id": "dune",
    "name": "Dune",
    "path": "./dune/",
    "preview": null
  },
  {
    "id": "grand-theft-chicken",
    "name": "Grand Theft Chicken",
    "path": "./grand-theft-chicken/",
    "preview": null
  }
]
